<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<RootNamespace>OSDC.Drilling.SurveyInstrument.Model</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<None Remove="docfx.json" />
	</ItemGroup>

	<ItemGroup>
		<Content Include="docfx.json">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<ExcludeFromSingleFile>true</ExcludeFromSingleFile>
			<CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
		</Content>
	</ItemGroup>

	<ItemGroup Condition="'$(UseLocalSurveyingProject)' != 'true'">
		<PackageReference Include="OSDC.DotnetLibraries.Drilling.Surveying" Version="1.3.4" />
		<PackageReference Include="OSDC.DotnetLibraries.General.DataManagement" Version="2.2.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(UseLocalSurveyingProject)' == 'true'">
		<ProjectReference Include="..\..\DotNetLibraries\OSDC.DotnetLibraries.General\OSDC.DotnetLibraries.Drilling.Surveying\OSDC.DotnetLibraries.Drilling.Surveying.csproj" />
		<PackageReference Include="OSDC.DotnetLibraries.General.DataManagement" Version="2.2.0" />
	</ItemGroup>

</Project>
